# Generated by Django 5.0.7 on 2024-12-30 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Practice',
            fields=[
                ('title_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SubTopic',
            fields=[
                ('subtopic_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('topic_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('role', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=50)),
                ('dob', models.CharField(max_length=15)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PracticeQuestion',
            fields=[
                ('question_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=100)),
                ('correct_option', models.IntegerField()),
                ('explanation', models.TextField()),
                ('title_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.practice')),
            ],
        ),
        migrations.CreateModel(
            name='PracticeOption',
            fields=[
                ('option_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('option1', models.CharField(max_length=100)),
                ('option2', models.CharField(max_length=100)),
                ('option3', models.CharField(max_length=100)),
                ('option4', models.CharField(max_length=100)),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.practicequestion')),
            ],
        ),
        migrations.AddField(
            model_name='practice',
            name='subtopic_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.subtopic'),
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('title_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=20)),
                ('subtopic_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.subtopic')),
                ('topic_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.topic')),
            ],
        ),
        migrations.CreateModel(
            name='TestHistory',
            fields=[
                ('test_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=20)),
                ('start_at', models.CharField(max_length=50)),
                ('finished_at', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=20)),
                ('score', models.IntegerField()),
                ('total_question', models.IntegerField()),
                ('subtopic_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.subtopic')),
                ('title_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.test')),
                ('topic_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.topic')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('report_id', models.AutoField(primary_key=True, serialize=False)),
                ('report', models.JSONField()),
                ('test_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.testhistory')),
            ],
        ),
        migrations.CreateModel(
            name='TestQuestion',
            fields=[
                ('question_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=100)),
                ('correct_option', models.IntegerField()),
                ('explanation', models.TextField()),
                ('title_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.test')),
            ],
        ),
        migrations.CreateModel(
            name='TestOption',
            fields=[
                ('option_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('option1', models.CharField(max_length=100)),
                ('option2', models.CharField(max_length=100)),
                ('option3', models.CharField(max_length=100)),
                ('option4', models.CharField(max_length=100)),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.testquestion')),
            ],
        ),
        migrations.AddField(
            model_name='subtopic',
            name='topic_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.topic'),
        ),
        migrations.AddField(
            model_name='practice',
            name='topic_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.topic'),
        ),
        migrations.AddField(
            model_name='topic',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user'),
        ),
        migrations.AddField(
            model_name='subtopic',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user'),
        ),
        migrations.CreateModel(
            name='LearningMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('subtopic_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.subtopic')),
                ('topic_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.topic')),
            ],
            options={
                'unique_together': {('topic_id', 'subtopic_id')},
            },
        ),
        migrations.CreateModel(
            name='UserTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_by', models.CharField(max_length=100)),
                ('created_at', models.CharField(max_length=50)),
                ('topic_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.topic')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
            options={
                'unique_together': {('user_id', 'topic_id')},
            },
        ),
    ]
